Profile page
Sokilskill/project-daily-energy-dose pull request #16
Opened 2024-01-15 21:02 UTC by opoberezh

2024-01-15 21:57 UTC, Sokilskill requested changes

2024-01-15 21:57 UTC, Sokilskill commented on vite.config.js
> +      src: './src',
для чого додавати крапку?

2024-01-15 21:57 UTC, Sokilskill commented on vite.config.js
> +      src: './src',
і виправте конфлікти

2024-01-15 21:59 UTC, opoberezh commented on vite.config.js
> +      src: './src',
тому що в мене не білдився проєкт без крапки

2024-01-15 22:00 UTC, opoberezh commented on vite.config.js
> +      src: './src',
конфлікти тільки в крапці?

2024-01-15 22:10 UTC, Sokilskill commented on vite.config.js
> +      src: './src',
конфлікти нижче по сторінці розписані.  З крапкою все лягяє.

2024-01-16 10:46 UTC, Sokilskill approved these changes

2024-01-16 11:07 UTC, merged