welcome-page
Sokilskill/project-daily-energy-dose pull request #7
Opened 2024-01-13 10:15 UTC by Lyst67

Сторінку пізніше доопрацюю, як обговорювали. Хедер в MainLayout  закоментував, бо в мене нема і він ламає.

2024-01-13 12:06 UTC, Sokilskill requested changes
переглянь зауваження, ХЕДЕР на всіх сторінках.
WElcome Містить: 
 - головний заголовок застосунку
 - список посилань на сторінки SignUp page та SignIn page

2024-01-13 12:06 UTC, Sokilskill commented on src/pages/WelcomePage/WelcomePage.module.css
> +.container {
використовуй  загальний container

2024-01-13 12:06 UTC, Sokilskill commented on src/pages/WelcomePage/WelcomePage.module.css
> +  background-image: url(../../assets/Welcome/images/people-training-gym-mob.webp),
картинки повинні бути 1x 2x webP і медіа правило

2024-01-13 12:06 UTC, Sokilskill commented on src/assets/Welcome/Icons/Icon.jsx
> +            <use href={Icons +"#icon-"+id}></use>
підключай свг через інтерполяцію, а також спрай вже є

2024-01-13 18:19 UTC, Sokilskill approved these changes
якщо картинка не підтягнеться

1. Фонові зображення зберегти в папку public/assets/ім'я_папки
2.  Змінити шлях  url('/assets/ім'я_папки/назва_файлу')

2024-01-13 18:19 UTC, merged

2024-01-13 18:57 UTC, Sokilskill reviewed
переглянь

2024-01-13 18:57 UTC, Sokilskill commented on src/pages/SignUpPage/SignUpPage.jsx
> +      <div className={style.container}>
<div className="container">

2024-01-13 18:57 UTC, Sokilskill commented on src/pages/SignUpPage/SignUpPage.jsx
> +    <div className={css.welcome_section}>
<section className={css.welcome_section}>

2024-01-13 18:57 UTC, Sokilskill commented on src/pages/WelcomePage/WelcomePage.jsx
> +      <div className={style.container}>
<div className="container">

2024-01-13 18:57 UTC, Sokilskill commented on src/pages/WelcomePage/WelcomePage.jsx
> +    <div className={css.welcome_section}>
< section className={css.welcome_body}>

2024-01-13 18:57 UTC, Sokilskill commented on src/pages/WelcomePage/WelcomePage.jsx
> +                 <button type="button" className={`${css.sing_btn} ${css.in}`} onClick={()=> navigate('ignin')}>Sign In</button>
navigate('/signin')

2024-01-14 07:48 UTC, Lyst67 commented
Ок. Побачив. Дякую.

13 січня 2024, 20:57:54, від "Serhii" ***@***.***>:


@Sokilskill commented on this pull request.
переглянь
In src/pages/SignUpPage/SignUpPage.jsx:
>  const SignUpPage = () => {
-  return <h3>SignUpPage</h3>;
+  //  const navigate = useNavigate()
+   
+  return (
+    <div className={css.welcome_section}>
+      <div className={style.container}>

In src/pages/SignUpPage/SignUpPage.jsx:
>  const SignUpPage = () => {
-  return <h3>SignUpPage</h3>;
+  //  const navigate = useNavigate()
+   
+  return (
+    <div className={css.welcome_section}>

In src/pages/WelcomePage/WelcomePage.jsx:
>  
 const WelcomePage = () => {
    const navigate = useNavigate()
    
   return (
-    <div className={css.welcome_body}>
-      <div className={css.container}>
-        <div className={css.logo}>
-          <Icon id="vector" className={css.icon_vector} />
-          <Icon id="power-pulse" className={css.icon_power}/>
-        </div>
+    <div className={css.welcome_section}>
+      <div className={style.container}>

In src/pages/WelcomePage/WelcomePage.jsx:
>  
 const WelcomePage = () => {
    const navigate = useNavigate()
    
   return (
-    <div className={css.welcome_body}>
-      <div className={css.container}>
-        <div className={css.logo}>
-          <Icon id="vector" className={css.icon_vector} />
-          <Icon id="power-pulse" className={css.icon_power}/>
-        </div>
+    <div className={css.welcome_section}>
< section className={css.welcome_body}>
In src/pages/WelcomePage/WelcomePage.jsx:
>                  </div>
            
                <div className={css.btns} >
-                 <button type="button" className={`${css.sing_btn} ${css.up} `} onClick={() => navigate('register')}>Sign Up</button>
-                 <button type="button" className={`${css.sing_btn} ${css.in}`} onClick={()=> navigate('login')}>Sign In</button>  
+                 <button type="button" className={`${css.sing_btn} ${css.up} `} onClick={() => navigate('signup')}>Sign Up</button>
+                 <button type="button" className={`${css.sing_btn} ${css.in}`} onClick={()=> navigate('ignin')}>Sign In</button>  
navigate('/signin')
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: ***@***.***>

--=-qcEIcO0blum4DVlcPdc1
Content-Type: text/html; charset="UTF-8"
Content-Transfer-Encoding: base64

PGh0bWw+PGJvZHk+PHNwYW4gc3R5bGU9ImRpc3BsYXk6YmxvY2s7IiBjbGFzcz0ieGZtXzUwMzc0
NzcxIj48ZGl2PjxzcGFuIHN0eWxlPSJmb250LXNpemU6MTJwdDtsaW5lLWhlaWdodDoxNHB0O2Zv
bnQtZmFtaWx5OkFyaWFsOyIgY2xhc3M9InhmbWMxIj7QntC6LiDQn9C+0LHQsNGH0LjQsi4g0JTR
j9C60YPRji48L3NwYW4+PGJyLz48L2Rpdj4NCjxkaXY+PGJyLz48L2Rpdj4NCjxkaXY+PGk+PHNw
YW4gc3R5bGU9ImZvbnQtc2l6ZToxMHB0O2xpbmUtaGVpZ2h0OjEycHQ7Ij48c3BhbiBzdHlsZT0i
Zm9udC1mYW1pbHk6QXJpYWw7Ij4xMyDRgdGW0YfQvdGPIDIwMjQsIDIwOjU3OjU0LCDQstGW0LQN
CiAgICAiU2VyaGlpIiAmbHQ7PC9zcGFuPjxhIGhyZWY9Im1haWx0bzpub3RpZmljYXRpb25zQGdp
dGh1Yi5jb20iIHRhcmdldD0iX2JsYW5rIj48c3BhbiBzdHlsZT0iZm9udC1mYW1pbHk6QXJpYWw7
Ij5ub3RpZmljYXRpb25zQGdpdGh1Yi5jb208L3NwYW4+PC9hPjxzcGFuIHN0eWxlPSJmb250LWZh
bWlseTpBcmlhbDsiPiZndDs6DQo8L3NwYW4+PC9zcGFuPjwvaT48L2Rpdj4NCjxkaXY+PGJyLz48
L2Rpdj4NCjxibG9ja3F1b3RlIHN0eWxlPSJib3JkZXItbGVmdDoxcHggc29saWQgI2NjY2NjYztt
YXJnaW46MHB4IDBweCAwcHggMC44ZXg7cGFkZGluZy1sZWZ0OjFleDsiPg0KPGRpdiBzdHlsZT0i
ZGlzcGxheTpibG9jazsiPg0KPGRpdj48L2Rpdj4NCjxkaXY+PGI+QFNva2lsc2tpbGw8L2I+IGNv
bW1lbnRlZCBvbiB0aGlzIHB1bGwgcmVxdWVzdC48L2Rpdj4NCjxkaXY+0L/QtdGA0LXQs9C70Y/Q
vdGMPC9kaXY+DQo8aHIvPjxkaXY+SW4gPGEgaHJlZj0iaHR0cHM6Ly9naXRodWIuY29tL1Nva2ls
c2tpbGwvcHJvamVjdC1kYWlseS1lbmVyZ3ktZG9zZS9wdWxsLzcjZGlzY3Vzc2lvbl9yMTQ1MTU4
ODQzMCIgdGFyZ2V0PSJfYmxhbmsiIHJlbD0ibm9yZWZlcnJlciBub29wZW5lciI+c3JjL3BhZ2Vz
L1NpZ25VcFBhZ2UvU2lnblVwUGFnZS5qc3g8L2E+OjwvZGl2Pg0KPHByZSBzdHlsZT0ibWFyZ2lu
OjVweCAwOyI+Jmd0OyAgY29uc3QgU2lnblVwUGFnZSA9ICgpID0mZ3Q7IHsNCi0gIHJldHVybiAm
bHQ7aDMmZ3Q7U2lnblVwUGFnZSZsdDsvaDMmZ3Q7Ow0KKyAgLy8gIGNvbnN0IG5hdmlnYXRlID0g
dXNlTmF2aWdhdGUoKQ0KKyAgIA0KKyAgcmV0dXJuICgNCisgICAgJmx0O2RpdiBjbGFzc05hbWU9
e2Nzcy53ZWxjb21lX3NlY3Rpb259Jmd0Ow0KKyAgICAgICZsdDtkaXYgY2xhc3NOYW1lPXtzdHls
ZS5jb250YWluZXJ9Jmd0Ow0KPC9wcmU+DQo8ZGl2PjwvZGl2Pg0KPGhyLz48ZGl2PkluIDxhIGhy
ZWY9Imh0dHBzOi8vZ2l0aHViLmNvbS9Tb2tpbHNraWxsL3Byb2plY3QtZGFpbHktZW5lcmd5LWRv
c2UvcHVsbC83I2Rpc2N1c3Npb25fcjE0NTE1ODg0NjQiIHRhcmdldD0iX2JsYW5rIiByZWw9Im5v
cmVmZXJyZXIgbm9vcGVuZXIiPnNyYy9wYWdlcy9TaWduVXBQYWdlL1NpZ25VcFBhZ2UuanN4PC9h
Pjo8L2Rpdj4NCjxwcmUgc3R5bGU9Im1hcmdpbjo1cHggMDsiPiZndDsgIGNvbnN0IFNpZ25VcFBh
Z2UgPSAoKSA9Jmd0OyB7DQotICByZXR1cm4gJmx0O2gzJmd0O1NpZ25VcFBhZ2UmbHQ7L2gzJmd0
OzsNCisgIC8vICBjb25zdCBuYXZpZ2F0ZSA9IHVzZU5hdmlnYXRlKCkNCisgICANCisgIHJldHVy
biAoDQorICAgICZsdDtkaXYgY2xhc3NOYW1lPXtjc3Mud2VsY29tZV9zZWN0aW9ufSZndDsNCjwv
cHJlPg0KPGRpdiBzdHlsZT0iZGlzcGxheTpibG9jazsiPjwvZGl2Pg0KPGhyLz48ZGl2PkluIDxh
IGhyZWY9Imh0dHBzOi8vZ2l0aHViLmNvbS9Tb2tpbHNraWxsL3Byb2plY3QtZGFpbHktZW5lcmd5
LWRvc2UvcHVsbC83I2Rpc2N1c3Npb25fcjE0NTE1ODg4MzgiIHRhcmdldD0iX2JsYW5rIiByZWw9
Im5vcmVmZXJyZXIgbm9vcGVuZXIiPnNyYy9wYWdlcy9XZWxjb21lUGFnZS9XZWxjb21lUGFnZS5q
c3g8L2E+OjwvZGl2Pg0KPHByZSBzdHlsZT0ibWFyZ2luOjVweCAwOyI+Jmd0OyAgDQogY29uc3Qg
V2VsY29tZVBhZ2UgPSAoKSA9Jmd0OyB7DQogICAgY29uc3QgbmF2aWdhdGUgPSB1c2VOYXZpZ2F0
ZSgpDQogICAgDQogICByZXR1cm4gKA0KLSAgICAmbHQ7ZGl2IGNsYXNzTmFtZT17Y3NzLndlbGNv
bWVfYm9keX0mZ3Q7DQotICAgICAgJmx0O2RpdiBjbGFzc05hbWU9e2Nzcy5jb250YWluZXJ9Jmd0
Ow0KLSAgICAgICAgJmx0O2RpdiBjbGFzc05hbWU9e2Nzcy5sb2dvfSZndDsNCi0gICAgICAgICAg
Jmx0O0ljb24gaWQ9InZlY3RvciIgY2xhc3NOYW1lPXtjc3MuaWNvbl92ZWN0b3J9IC8mZ3Q7DQot
ICAgICAgICAgICZsdDtJY29uIGlkPSJwb3dlci1wdWxzZSIgY2xhc3NOYW1lPXtjc3MuaWNvbl9w
b3dlcn0vJmd0Ow0KLSAgICAgICAgJmx0Oy9kaXYmZ3Q7DQorICAgICZsdDtkaXYgY2xhc3NOYW1l
PXtjc3Mud2VsY29tZV9zZWN0aW9ufSZndDsNCisgICAgICAmbHQ7ZGl2IGNsYXNzTmFtZT17c3R5
bGUuY29udGFpbmVyfSZndDsNCjwvcHJlPg0KPGRpdj48L2Rpdj4NCjxoci8+PGRpdj5JbiA8YSBo
cmVmPSJodHRwczovL2dpdGh1Yi5jb20vU29raWxza2lsbC9wcm9qZWN0LWRhaWx5LWVuZXJneS1k
b3NlL3B1bGwvNyNkaXNjdXNzaW9uX3IxNDUxNTg4ODgzIiB0YXJnZXQ9Il9ibGFuayIgcmVsPSJu
b3JlZmVycmVyIG5vb3BlbmVyIj5zcmMvcGFnZXMvV2VsY29tZVBhZ2UvV2VsY29tZVBhZ2UuanN4
PC9hPjo8L2Rpdj4NCjxwcmUgc3R5bGU9Im1hcmdpbjo1cHggMDsiPiZndDsgIA0KIGNvbnN0IFdl
bGNvbWVQYWdlID0gKCkgPSZndDsgew0KICAgIGNvbnN0IG5hdmlnYXRlID0gdXNlTmF2aWdhdGUo
KQ0KICAgIA0KICAgcmV0dXJuICgNCi0gICAgJmx0O2RpdiBjbGFzc05hbWU9e2Nzcy53ZWxjb21l
X2JvZHl9Jmd0Ow0KLSAgICAgICZsdDtkaXYgY2xhc3NOYW1lPXtjc3MuY29udGFpbmVyfSZndDsN
Ci0gICAgICAgICZsdDtkaXYgY2xhc3NOYW1lPXtjc3MubG9nb30mZ3Q7DQotICAgICAgICAgICZs
dDtJY29uIGlkPSJ2ZWN0b3IiIGNsYXNzTmFtZT17Y3NzLmljb25fdmVjdG9yfSAvJmd0Ow0KLSAg
ICAgICAgICAmbHQ7SWNvbiBpZD0icG93ZXItcHVsc2UiIGNsYXNzTmFtZT17Y3NzLmljb25fcG93
ZXJ9LyZndDsNCi0gICAgICAgICZsdDsvZGl2Jmd0Ow0KKyAgICAmbHQ7ZGl2IGNsYXNzTmFtZT17
Y3NzLndlbGNvbWVfc2VjdGlvbn0mZ3Q7DQo8L3ByZT4NCjxkaXY+Jmx0OyBzZWN0aW9uIGNsYXNz
TmFtZT17Y3NzLndlbGNvbWVfYm9keX0mZ3Q7PC9kaXY+DQo8aHIvPjxkaXY+SW4gPGEgaHJlZj0i
aHR0cHM6Ly9naXRodWIuY29tL1Nva2lsc2tpbGwvcHJvamVjdC1kYWlseS1lbmVyZ3ktZG9zZS9w
dWxsLzcjZGlzY3Vzc2lvbl9yMTQ1MTU4ODk3MyIgdGFyZ2V0PSJfYmxhbmsiIHJlbD0ibm9yZWZl
cnJlciBub29wZW5lciI+c3JjL3BhZ2VzL1dlbGNvbWVQYWdlL1dlbGNvbWVQYWdlLmpzeDwvYT46
PC9kaXY+DQo8cHJlIHN0eWxlPSJtYXJnaW46NXB4IDA7Ij4mZ3Q7ICAgICAgICAgICAgICAgICAg
Jmx0Oy9kaXYmZ3Q7DQogICAgICAgICAgICANCiAgICAgICAgICAgICAgICAmbHQ7ZGl2IGNsYXNz
TmFtZT17Y3NzLmJ0bnN9ICZndDsNCi0gICAgICAgICAgICAgICAgICZsdDtidXR0b24gdHlwZT0i
YnV0dG9uIiBjbGFzc05hbWU9e2Ake2Nzcy5zaW5nX2J0bn0gJHtjc3MudXB9IGB9IG9uQ2xpY2s9
eygpID0mZ3Q7IG5hdmlnYXRlKCdyZWdpc3RlcicpfSZndDtTaWduIFVwJmx0Oy9idXR0b24mZ3Q7
DQotICAgICAgICAgICAgICAgICAmbHQ7YnV0dG9uIHR5cGU9ImJ1dHRvbiIgY2xhc3NOYW1lPXtg
JHtjc3Muc2luZ19idG59ICR7Y3NzLmlufWB9IG9uQ2xpY2s9eygpPSZndDsgbmF2aWdhdGUoJ2xv
Z2luJyl9Jmd0O1NpZ24gSW4mbHQ7L2J1dHRvbiZndDsgIA0KKyAgICAgICAgICAgICAgICAgJmx0
O2J1dHRvbiB0eXBlPSJidXR0b24iIGNsYXNzTmFtZT17YCR7Y3NzLnNpbmdfYnRufSAke2Nzcy51
cH0gYH0gb25DbGljaz17KCkgPSZndDsgbmF2aWdhdGUoJ3NpZ251cCcpfSZndDtTaWduIFVwJmx0
Oy9idXR0b24mZ3Q7DQorICAgICAgICAgICAgICAgICAmbHQ7YnV0dG9uIHR5cGU9ImJ1dHRvbiIg
Y2xhc3NOYW1lPXtgJHtjc3Muc2luZ19idG59ICR7Y3NzLmlufWB9IG9uQ2xpY2s9eygpPSZndDsg
bmF2aWdhdGUoJ2lnbmluJyl9Jmd0O1 [...]